version: "3.7"
services:
    app:
      container_name: api
      image: node:20
      working_dir: /usr/src/app
      tty: true
      ports:
      - '3000:3000'
      volumes:
        - ./:/usr/src/app
      networks:
        - todo-network
      depends_on:
        - db

    db:
      container_name: mysql
      image: mysql:8.0
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: pass
        MYSQL_DATABASE: todo
        MYSQL_USER: todoUser
        MYSQL_PASSWORD: todopass
        TZ: "Asia/Tokyo"
      volumes:
        - todo-data:/var/lib/mysql
      restart: always
      networks:
        - todo-network

networks:
  todo-network:

volumes:
  todo-data: